/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalletRouteRouteImport } from './routes/wallet/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCredentialsRouteImport } from './routes/app/credentials'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppIssueRouteImport } from './routes/app/issue'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as AppLedgerRouteImport } from './routes/app/ledger'
import { Route as AppStatusRouteImport } from './routes/app/status'
import { Route as AppWebhooksRouteImport } from './routes/app/webhooks'
import { Route as DidWebSlugRouteImport } from './routes/did-web.$slug'
import { Route as DidMultibaseRouteImport } from './routes/did.$multibase'
import { Route as EvidenceRefRouteImport } from './routes/evidence.$ref'
import { Route as PresentRefRouteImport } from './routes/present.$ref'
import { Route as ReportRefRouteImport } from './routes/report.$ref'
import { Route as StatusIdRouteImport } from './routes/status.$id'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyRefRouteImport } from './routes/verify/$ref'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1VerifyRouteImport } from './routes/api/v1/verify'
import { Route as WalletClaimTokenRouteImport } from './routes/wallet/claim.$token'
import { Route as ApiV1DidWebSlugRouteImport } from './routes/api/v1/did-web.$slug'
import { Route as ApiV1EvidenceRefRouteImport } from './routes/api/v1/evidence.$ref'
import { Route as ApiV1ReportsRefRouteImport } from './routes/api/v1/reports.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRouteRoute = WalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssueRoute = AppIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRouteRoute,
} as any)
const DidWebSlugRoute = DidWebSlugRouteImport.update({
  id: '/did-web/$slug',
  path: '/did-web/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DidMultibaseRoute = DidMultibaseRouteImport.update({
  id: '/did/$multibase',
  path: '/did/$multibase',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRefRoute = EvidenceRefRouteImport.update({
  id: '/evidence/$ref',
  path: '/evidence/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRefRoute = PresentRefRouteImport.update({
  id: '/present/$ref',
  path: '/present/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRefRoute = ReportRefRouteImport.update({
  id: '/report/$ref',
  path: '/report/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIdRoute = StatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRefRoute = VerifyRefRouteImport.update({
  id: '/verify/$ref',
  path: '/verify/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VerifyRoute = ApiV1VerifyRouteImport.update({
  id: '/api/v1/verify',
  path: '/api/v1/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletClaimTokenRoute = WalletClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => WalletRouteRoute,
} as any)
const ApiV1DidWebSlugRoute = ApiV1DidWebSlugRouteImport.update({
  id: '/api/v1/did-web/$slug',
  path: '/api/v1/did-web/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EvidenceRefRoute = ApiV1EvidenceRefRouteImport.update({
  id: '/api/v1/evidence/$ref',
  path: '/api/v1/evidence/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsRefRoute = ApiV1ReportsRefRouteImport.update({
  id: '/api/v1/reports/$ref',
  path: '/api/v1/reports/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app': typeof AppIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/wallet'
    | '/compliance'
    | '/developers'
    | '/login'
    | '/trust'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/present/$ref'
    | '/report/$ref'
    | '/status/$id'
    | '/verify/$ref'
    | '/app/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/reports/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/developers'
    | '/login'
    | '/trust'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/present/$ref'
    | '/report/$ref'
    | '/status/$id'
    | '/verify/$ref'
    | '/app'
    | '/verify'
    | '/wallet'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/reports/$ref'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/wallet'
    | '/compliance'
    | '/developers'
    | '/login'
    | '/trust'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/present/$ref'
    | '/report/$ref'
    | '/status/$id'
    | '/verify/$ref'
    | '/app/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/reports/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WalletRouteRoute: typeof WalletRouteRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  DevelopersRoute: typeof DevelopersRoute
  LoginRoute: typeof LoginRoute
  TrustRoute: typeof TrustRoute
  DidWebSlugRoute: typeof DidWebSlugRoute
  DidMultibaseRoute: typeof DidMultibaseRoute
  EvidenceRefRoute: typeof EvidenceRefRoute
  PresentRefRoute: typeof PresentRefRoute
  ReportRefRoute: typeof ReportRefRoute
  StatusIdRoute: typeof StatusIdRoute
  VerifyRefRoute: typeof VerifyRefRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1VerifyRoute: typeof ApiV1VerifyRoute
  ApiV1DidWebSlugRoute: typeof ApiV1DidWebSlugRoute
  ApiV1EvidenceRefRoute: typeof ApiV1EvidenceRefRoute
  ApiV1ReportsRefRoute: typeof ApiV1ReportsRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/credentials': {
      id: '/app/credentials'
      path: '/credentials'
      fullPath: '/app/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/issue': {
      id: '/app/issue'
      path: '/issue'
      fullPath: '/app/issue'
      preLoaderRoute: typeof AppIssueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/status': {
      id: '/app/status'
      path: '/status'
      fullPath: '/app/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/did-web/$slug': {
      id: '/did-web/$slug'
      path: '/did-web/$slug'
      fullPath: '/did-web/$slug'
      preLoaderRoute: typeof DidWebSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/did/$multibase': {
      id: '/did/$multibase'
      path: '/did/$multibase'
      fullPath: '/did/$multibase'
      preLoaderRoute: typeof DidMultibaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$ref': {
      id: '/evidence/$ref'
      path: '/evidence/$ref'
      fullPath: '/evidence/$ref'
      preLoaderRoute: typeof EvidenceRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$ref': {
      id: '/present/$ref'
      path: '/present/$ref'
      fullPath: '/present/$ref'
      preLoaderRoute: typeof PresentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ref': {
      id: '/report/$ref'
      path: '/report/$ref'
      fullPath: '/report/$ref'
      preLoaderRoute: typeof ReportRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$id': {
      id: '/status/$id'
      path: '/status/$id'
      fullPath: '/status/$id'
      preLoaderRoute: typeof StatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ref': {
      id: '/verify/$ref'
      path: '/verify/$ref'
      fullPath: '/verify/$ref'
      preLoaderRoute: typeof VerifyRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/verify': {
      id: '/api/v1/verify'
      path: '/api/v1/verify'
      fullPath: '/api/v1/verify'
      preLoaderRoute: typeof ApiV1VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/claim/$token': {
      id: '/wallet/claim/$token'
      path: '/claim/$token'
      fullPath: '/wallet/claim/$token'
      preLoaderRoute: typeof WalletClaimTokenRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/api/v1/did-web/$slug': {
      id: '/api/v1/did-web/$slug'
      path: '/api/v1/did-web/$slug'
      fullPath: '/api/v1/did-web/$slug'
      preLoaderRoute: typeof ApiV1DidWebSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence/$ref': {
      id: '/api/v1/evidence/$ref'
      path: '/api/v1/evidence/$ref'
      fullPath: '/api/v1/evidence/$ref'
      preLoaderRoute: typeof ApiV1EvidenceRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/$ref': {
      id: '/api/v1/reports/$ref'
      path: '/api/v1/reports/$ref'
      fullPath: '/api/v1/reports/$ref'
      preLoaderRoute: typeof ApiV1ReportsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppIssueRoute: typeof AppIssueRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppStatusRoute: typeof AppStatusRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditRoute: AppAuditRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppIssueRoute: AppIssueRoute,
  AppKeysRoute: AppKeysRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppStatusRoute: AppStatusRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WalletRouteRouteChildren {
  WalletIndexRoute: typeof WalletIndexRoute
  WalletClaimTokenRoute: typeof WalletClaimTokenRoute
}

const WalletRouteRouteChildren: WalletRouteRouteChildren = {
  WalletIndexRoute: WalletIndexRoute,
  WalletClaimTokenRoute: WalletClaimTokenRoute,
}

const WalletRouteRouteWithChildren = WalletRouteRoute._addFileChildren(
  WalletRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  WalletRouteRoute: WalletRouteRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  DevelopersRoute: DevelopersRoute,
  LoginRoute: LoginRoute,
  TrustRoute: TrustRoute,
  DidWebSlugRoute: DidWebSlugRoute,
  DidMultibaseRoute: DidMultibaseRoute,
  EvidenceRefRoute: EvidenceRefRoute,
  PresentRefRoute: PresentRefRoute,
  ReportRefRoute: ReportRefRoute,
  StatusIdRoute: StatusIdRoute,
  VerifyRefRoute: VerifyRefRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1VerifyRoute: ApiV1VerifyRoute,
  ApiV1DidWebSlugRoute: ApiV1DidWebSlugRoute,
  ApiV1EvidenceRefRoute: ApiV1EvidenceRefRoute,
  ApiV1ReportsRefRoute: ApiV1ReportsRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
