/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as SdJwtRouteImport } from './routes/sd-jwt'
import { Route as Soc2RouteImport } from './routes/soc2'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalletRouteRouteImport } from './routes/wallet/route'
import { Route as DotwellKnownOpenidCredentialIssuerRouteImport } from './routes/[.]well-known/openid-credential-issuer'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCredentialsRouteImport } from './routes/app/credentials'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppIssueRouteImport } from './routes/app/issue'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as AppLedgerRouteImport } from './routes/app/ledger'
import { Route as AppStatusRouteImport } from './routes/app/status'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as AppWebhooksRouteImport } from './routes/app/webhooks'
import { Route as DidWebSlugRouteImport } from './routes/did-web.$slug'
import { Route as DidMultibaseRouteImport } from './routes/did.$multibase'
import { Route as EvidenceRefRouteImport } from './routes/evidence.$ref'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as Oid4vciIndexRouteImport } from './routes/oid4vci/index'
import { Route as Oid4vpIndexRouteImport } from './routes/oid4vp/index'
import { Route as Oid4vpIdRouteImport } from './routes/oid4vp/$id'
import { Route as PresentRefRouteImport } from './routes/present.$ref'
import { Route as ReportRefRouteImport } from './routes/report.$ref'
import { Route as SchemasUniversityDegreeRouteImport } from './routes/schemas/university-degree'
import { Route as SchemasUniversityDegreeCredentialDotjsonRouteImport } from './routes/schemas/university-degree-credential[.]json'
import { Route as StatusIdRouteImport } from './routes/status.$id'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyRefRouteImport } from './routes/verify/$ref'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1VerifyRouteImport } from './routes/api/v1/verify'
import { Route as CredentialsStatusIdRouteImport } from './routes/credentials/status.$id'
import { Route as WalletClaimTokenRouteImport } from './routes/wallet/claim.$token'
import { Route as ApiV1DidWebSlugRouteImport } from './routes/api/v1/did-web.$slug'
import { Route as ApiV1EvidenceRefRouteImport } from './routes/api/v1/evidence.$ref'
import { Route as ApiV1LedgerChainRouteImport } from './routes/api/v1/ledger.chain'
import { Route as ApiV1LedgerProofRouteImport } from './routes/api/v1/ledger.proof'
import { Route as ApiV1LedgerVerifyRouteImport } from './routes/api/v1/ledger.verify'
import { Route as ApiV1Oid4vciCredentialRouteImport } from './routes/api/v1/oid4vci/credential'
import { Route as ApiV1Oid4vciMetadataRouteImport } from './routes/api/v1/oid4vci/metadata'
import { Route as ApiV1Oid4vciPreviewWalletRouteImport } from './routes/api/v1/oid4vci/preview-wallet'
import { Route as ApiV1Oid4vciTokenRouteImport } from './routes/api/v1/oid4vci/token'
import { Route as ApiV1Oid4vpRequestsRouteImport } from './routes/api/v1/oid4vp/requests'
import { Route as ApiV1ReportsRefRouteImport } from './routes/api/v1/reports.$ref'
import { Route as ApiV1LedgerProofVerifyRouteImport } from './routes/api/v1/ledger.proof.verify'
import { Route as ApiV1Oid4vciOfferTokenRouteImport } from './routes/api/v1/oid4vci/offer.$token'
import { Route as ApiV1Oid4vpDirectPostIdRouteImport } from './routes/api/v1/oid4vp/direct-post.$id'
import { Route as ApiV1Oid4vpPreviewWalletIdRouteImport } from './routes/api/v1/oid4vp/preview-wallet.$id'
import { Route as ApiV1Oid4vpRequestIdRouteImport } from './routes/api/v1/oid4vp/request.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const SdJwtRoute = SdJwtRouteImport.update({
  id: '/sd-jwt',
  path: '/sd-jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const Soc2Route = Soc2RouteImport.update({
  id: '/soc2',
  path: '/soc2',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRouteRoute = WalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidCredentialIssuerRoute =
  DotwellKnownOpenidCredentialIssuerRouteImport.update({
    id: '/.well-known/openid-credential-issuer',
    path: '/.well-known/openid-credential-issuer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssueRoute = AppIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRouteRoute,
} as any)
const DidWebSlugRoute = DidWebSlugRouteImport.update({
  id: '/did-web/$slug',
  path: '/did-web/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DidMultibaseRoute = DidMultibaseRouteImport.update({
  id: '/did/$multibase',
  path: '/did/$multibase',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRefRoute = EvidenceRefRouteImport.update({
  id: '/evidence/$ref',
  path: '/evidence/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Oid4vciIndexRoute = Oid4vciIndexRouteImport.update({
  id: '/oid4vci/',
  path: '/oid4vci/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oid4vpIndexRoute = Oid4vpIndexRouteImport.update({
  id: '/oid4vp/',
  path: '/oid4vp/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oid4vpIdRoute = Oid4vpIdRouteImport.update({
  id: '/oid4vp/$id',
  path: '/oid4vp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRefRoute = PresentRefRouteImport.update({
  id: '/present/$ref',
  path: '/present/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRefRoute = ReportRefRouteImport.update({
  id: '/report/$ref',
  path: '/report/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasUniversityDegreeRoute = SchemasUniversityDegreeRouteImport.update({
  id: '/schemas/university-degree',
  path: '/schemas/university-degree',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasUniversityDegreeCredentialDotjsonRoute =
  SchemasUniversityDegreeCredentialDotjsonRouteImport.update({
    id: '/schemas/university-degree-credential.json',
    path: '/schemas/university-degree-credential.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatusIdRoute = StatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRefRoute = VerifyRefRouteImport.update({
  id: '/verify/$ref',
  path: '/verify/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VerifyRoute = ApiV1VerifyRouteImport.update({
  id: '/api/v1/verify',
  path: '/api/v1/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsStatusIdRoute = CredentialsStatusIdRouteImport.update({
  id: '/credentials/status/$id',
  path: '/credentials/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletClaimTokenRoute = WalletClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => WalletRouteRoute,
} as any)
const ApiV1DidWebSlugRoute = ApiV1DidWebSlugRouteImport.update({
  id: '/api/v1/did-web/$slug',
  path: '/api/v1/did-web/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EvidenceRefRoute = ApiV1EvidenceRefRouteImport.update({
  id: '/api/v1/evidence/$ref',
  path: '/api/v1/evidence/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LedgerChainRoute = ApiV1LedgerChainRouteImport.update({
  id: '/api/v1/ledger/chain',
  path: '/api/v1/ledger/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LedgerProofRoute = ApiV1LedgerProofRouteImport.update({
  id: '/api/v1/ledger/proof',
  path: '/api/v1/ledger/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LedgerVerifyRoute = ApiV1LedgerVerifyRouteImport.update({
  id: '/api/v1/ledger/verify',
  path: '/api/v1/ledger/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vciCredentialRoute = ApiV1Oid4vciCredentialRouteImport.update({
  id: '/api/v1/oid4vci/credential',
  path: '/api/v1/oid4vci/credential',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vciMetadataRoute = ApiV1Oid4vciMetadataRouteImport.update({
  id: '/api/v1/oid4vci/metadata',
  path: '/api/v1/oid4vci/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vciPreviewWalletRoute =
  ApiV1Oid4vciPreviewWalletRouteImport.update({
    id: '/api/v1/oid4vci/preview-wallet',
    path: '/api/v1/oid4vci/preview-wallet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1Oid4vciTokenRoute = ApiV1Oid4vciTokenRouteImport.update({
  id: '/api/v1/oid4vci/token',
  path: '/api/v1/oid4vci/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vpRequestsRoute = ApiV1Oid4vpRequestsRouteImport.update({
  id: '/api/v1/oid4vp/requests',
  path: '/api/v1/oid4vp/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsRefRoute = ApiV1ReportsRefRouteImport.update({
  id: '/api/v1/reports/$ref',
  path: '/api/v1/reports/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LedgerProofVerifyRoute = ApiV1LedgerProofVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiV1LedgerProofRoute,
} as any)
const ApiV1Oid4vciOfferTokenRoute = ApiV1Oid4vciOfferTokenRouteImport.update({
  id: '/api/v1/oid4vci/offer/$token',
  path: '/api/v1/oid4vci/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vpDirectPostIdRoute = ApiV1Oid4vpDirectPostIdRouteImport.update({
  id: '/api/v1/oid4vp/direct-post/$id',
  path: '/api/v1/oid4vp/direct-post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Oid4vpPreviewWalletIdRoute =
  ApiV1Oid4vpPreviewWalletIdRouteImport.update({
    id: '/api/v1/oid4vp/preview-wallet/$id',
    path: '/api/v1/oid4vp/preview-wallet/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1Oid4vpRequestIdRoute = ApiV1Oid4vpRequestIdRouteImport.update({
  id: '/api/v1/oid4vp/request/$id',
  path: '/api/v1/oid4vp/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/chain': typeof ChainRoute
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/healthz': typeof HealthzRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/readyz': typeof ReadyzRoute
  '/sd-jwt': typeof SdJwtRoute
  '/soc2': typeof Soc2Route
  '/trust': typeof TrustRoute
  '/.well-known/openid-credential-issuer': typeof DotwellKnownOpenidCredentialIssuerRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/team': typeof AppTeamRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oid4vp/$id': typeof Oid4vpIdRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/schemas/university-degree': typeof SchemasUniversityDegreeRoute
  '/schemas/university-degree-credential.json': typeof SchemasUniversityDegreeCredentialDotjsonRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/oid4vci/': typeof Oid4vciIndexRoute
  '/oid4vp/': typeof Oid4vpIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/credentials/status/$id': typeof CredentialsStatusIdRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/ledger/chain': typeof ApiV1LedgerChainRoute
  '/api/v1/ledger/proof': typeof ApiV1LedgerProofRouteWithChildren
  '/api/v1/ledger/verify': typeof ApiV1LedgerVerifyRoute
  '/api/v1/oid4vci/credential': typeof ApiV1Oid4vciCredentialRoute
  '/api/v1/oid4vci/metadata': typeof ApiV1Oid4vciMetadataRoute
  '/api/v1/oid4vci/preview-wallet': typeof ApiV1Oid4vciPreviewWalletRoute
  '/api/v1/oid4vci/token': typeof ApiV1Oid4vciTokenRoute
  '/api/v1/oid4vp/requests': typeof ApiV1Oid4vpRequestsRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
  '/api/v1/ledger/proof/verify': typeof ApiV1LedgerProofVerifyRoute
  '/api/v1/oid4vci/offer/$token': typeof ApiV1Oid4vciOfferTokenRoute
  '/api/v1/oid4vp/direct-post/$id': typeof ApiV1Oid4vpDirectPostIdRoute
  '/api/v1/oid4vp/preview-wallet/$id': typeof ApiV1Oid4vpPreviewWalletIdRoute
  '/api/v1/oid4vp/request/$id': typeof ApiV1Oid4vpRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chain': typeof ChainRoute
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/healthz': typeof HealthzRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/readyz': typeof ReadyzRoute
  '/sd-jwt': typeof SdJwtRoute
  '/soc2': typeof Soc2Route
  '/trust': typeof TrustRoute
  '/.well-known/openid-credential-issuer': typeof DotwellKnownOpenidCredentialIssuerRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/team': typeof AppTeamRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oid4vp/$id': typeof Oid4vpIdRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/schemas/university-degree': typeof SchemasUniversityDegreeRoute
  '/schemas/university-degree-credential.json': typeof SchemasUniversityDegreeCredentialDotjsonRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app': typeof AppIndexRoute
  '/oid4vci': typeof Oid4vciIndexRoute
  '/oid4vp': typeof Oid4vpIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/credentials/status/$id': typeof CredentialsStatusIdRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/ledger/chain': typeof ApiV1LedgerChainRoute
  '/api/v1/ledger/proof': typeof ApiV1LedgerProofRouteWithChildren
  '/api/v1/ledger/verify': typeof ApiV1LedgerVerifyRoute
  '/api/v1/oid4vci/credential': typeof ApiV1Oid4vciCredentialRoute
  '/api/v1/oid4vci/metadata': typeof ApiV1Oid4vciMetadataRoute
  '/api/v1/oid4vci/preview-wallet': typeof ApiV1Oid4vciPreviewWalletRoute
  '/api/v1/oid4vci/token': typeof ApiV1Oid4vciTokenRoute
  '/api/v1/oid4vp/requests': typeof ApiV1Oid4vpRequestsRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
  '/api/v1/ledger/proof/verify': typeof ApiV1LedgerProofVerifyRoute
  '/api/v1/oid4vci/offer/$token': typeof ApiV1Oid4vciOfferTokenRoute
  '/api/v1/oid4vp/direct-post/$id': typeof ApiV1Oid4vpDirectPostIdRoute
  '/api/v1/oid4vp/preview-wallet/$id': typeof ApiV1Oid4vpPreviewWalletIdRoute
  '/api/v1/oid4vp/request/$id': typeof ApiV1Oid4vpRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/chain': typeof ChainRoute
  '/compliance': typeof ComplianceRoute
  '/developers': typeof DevelopersRoute
  '/healthz': typeof HealthzRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/readyz': typeof ReadyzRoute
  '/sd-jwt': typeof SdJwtRoute
  '/soc2': typeof Soc2Route
  '/trust': typeof TrustRoute
  '/.well-known/openid-credential-issuer': typeof DotwellKnownOpenidCredentialIssuerRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/status': typeof AppStatusRoute
  '/app/team': typeof AppTeamRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/did-web/$slug': typeof DidWebSlugRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/evidence/$ref': typeof EvidenceRefRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oid4vp/$id': typeof Oid4vpIdRoute
  '/present/$ref': typeof PresentRefRoute
  '/report/$ref': typeof ReportRefRoute
  '/schemas/university-degree': typeof SchemasUniversityDegreeRoute
  '/schemas/university-degree-credential.json': typeof SchemasUniversityDegreeCredentialDotjsonRoute
  '/status/$id': typeof StatusIdRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/oid4vci/': typeof Oid4vciIndexRoute
  '/oid4vp/': typeof Oid4vpIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/verify': typeof ApiV1VerifyRoute
  '/credentials/status/$id': typeof CredentialsStatusIdRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
  '/api/v1/did-web/$slug': typeof ApiV1DidWebSlugRoute
  '/api/v1/evidence/$ref': typeof ApiV1EvidenceRefRoute
  '/api/v1/ledger/chain': typeof ApiV1LedgerChainRoute
  '/api/v1/ledger/proof': typeof ApiV1LedgerProofRouteWithChildren
  '/api/v1/ledger/verify': typeof ApiV1LedgerVerifyRoute
  '/api/v1/oid4vci/credential': typeof ApiV1Oid4vciCredentialRoute
  '/api/v1/oid4vci/metadata': typeof ApiV1Oid4vciMetadataRoute
  '/api/v1/oid4vci/preview-wallet': typeof ApiV1Oid4vciPreviewWalletRoute
  '/api/v1/oid4vci/token': typeof ApiV1Oid4vciTokenRoute
  '/api/v1/oid4vp/requests': typeof ApiV1Oid4vpRequestsRoute
  '/api/v1/reports/$ref': typeof ApiV1ReportsRefRoute
  '/api/v1/ledger/proof/verify': typeof ApiV1LedgerProofVerifyRoute
  '/api/v1/oid4vci/offer/$token': typeof ApiV1Oid4vciOfferTokenRoute
  '/api/v1/oid4vp/direct-post/$id': typeof ApiV1Oid4vpDirectPostIdRoute
  '/api/v1/oid4vp/preview-wallet/$id': typeof ApiV1Oid4vpPreviewWalletIdRoute
  '/api/v1/oid4vp/request/$id': typeof ApiV1Oid4vpRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/wallet'
    | '/chain'
    | '/compliance'
    | '/developers'
    | '/healthz'
    | '/legal'
    | '/login'
    | '/ops'
    | '/readyz'
    | '/sd-jwt'
    | '/soc2'
    | '/trust'
    | '/.well-known/openid-credential-issuer'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/team'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/invite/$token'
    | '/oid4vp/$id'
    | '/present/$ref'
    | '/report/$ref'
    | '/schemas/university-degree'
    | '/schemas/university-degree-credential.json'
    | '/status/$id'
    | '/verify/$ref'
    | '/app/'
    | '/oid4vci/'
    | '/oid4vp/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/credentials/status/$id'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/ledger/chain'
    | '/api/v1/ledger/proof'
    | '/api/v1/ledger/verify'
    | '/api/v1/oid4vci/credential'
    | '/api/v1/oid4vci/metadata'
    | '/api/v1/oid4vci/preview-wallet'
    | '/api/v1/oid4vci/token'
    | '/api/v1/oid4vp/requests'
    | '/api/v1/reports/$ref'
    | '/api/v1/ledger/proof/verify'
    | '/api/v1/oid4vci/offer/$token'
    | '/api/v1/oid4vp/direct-post/$id'
    | '/api/v1/oid4vp/preview-wallet/$id'
    | '/api/v1/oid4vp/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chain'
    | '/compliance'
    | '/developers'
    | '/healthz'
    | '/legal'
    | '/login'
    | '/ops'
    | '/readyz'
    | '/sd-jwt'
    | '/soc2'
    | '/trust'
    | '/.well-known/openid-credential-issuer'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/team'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/invite/$token'
    | '/oid4vp/$id'
    | '/present/$ref'
    | '/report/$ref'
    | '/schemas/university-degree'
    | '/schemas/university-degree-credential.json'
    | '/status/$id'
    | '/verify/$ref'
    | '/app'
    | '/oid4vci'
    | '/oid4vp'
    | '/verify'
    | '/wallet'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/credentials/status/$id'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/ledger/chain'
    | '/api/v1/ledger/proof'
    | '/api/v1/ledger/verify'
    | '/api/v1/oid4vci/credential'
    | '/api/v1/oid4vci/metadata'
    | '/api/v1/oid4vci/preview-wallet'
    | '/api/v1/oid4vci/token'
    | '/api/v1/oid4vp/requests'
    | '/api/v1/reports/$ref'
    | '/api/v1/ledger/proof/verify'
    | '/api/v1/oid4vci/offer/$token'
    | '/api/v1/oid4vp/direct-post/$id'
    | '/api/v1/oid4vp/preview-wallet/$id'
    | '/api/v1/oid4vp/request/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/wallet'
    | '/chain'
    | '/compliance'
    | '/developers'
    | '/healthz'
    | '/legal'
    | '/login'
    | '/ops'
    | '/readyz'
    | '/sd-jwt'
    | '/soc2'
    | '/trust'
    | '/.well-known/openid-credential-issuer'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/app/status'
    | '/app/team'
    | '/app/webhooks'
    | '/did-web/$slug'
    | '/did/$multibase'
    | '/evidence/$ref'
    | '/invite/$token'
    | '/oid4vp/$id'
    | '/present/$ref'
    | '/report/$ref'
    | '/schemas/university-degree'
    | '/schemas/university-degree-credential.json'
    | '/status/$id'
    | '/verify/$ref'
    | '/app/'
    | '/oid4vci/'
    | '/oid4vp/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/verify'
    | '/credentials/status/$id'
    | '/wallet/claim/$token'
    | '/api/v1/did-web/$slug'
    | '/api/v1/evidence/$ref'
    | '/api/v1/ledger/chain'
    | '/api/v1/ledger/proof'
    | '/api/v1/ledger/verify'
    | '/api/v1/oid4vci/credential'
    | '/api/v1/oid4vci/metadata'
    | '/api/v1/oid4vci/preview-wallet'
    | '/api/v1/oid4vci/token'
    | '/api/v1/oid4vp/requests'
    | '/api/v1/reports/$ref'
    | '/api/v1/ledger/proof/verify'
    | '/api/v1/oid4vci/offer/$token'
    | '/api/v1/oid4vp/direct-post/$id'
    | '/api/v1/oid4vp/preview-wallet/$id'
    | '/api/v1/oid4vp/request/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WalletRouteRoute: typeof WalletRouteRouteWithChildren
  ChainRoute: typeof ChainRoute
  ComplianceRoute: typeof ComplianceRoute
  DevelopersRoute: typeof DevelopersRoute
  HealthzRoute: typeof HealthzRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  ReadyzRoute: typeof ReadyzRoute
  SdJwtRoute: typeof SdJwtRoute
  Soc2Route: typeof Soc2Route
  TrustRoute: typeof TrustRoute
  DotwellKnownOpenidCredentialIssuerRoute: typeof DotwellKnownOpenidCredentialIssuerRoute
  DidWebSlugRoute: typeof DidWebSlugRoute
  DidMultibaseRoute: typeof DidMultibaseRoute
  EvidenceRefRoute: typeof EvidenceRefRoute
  InviteTokenRoute: typeof InviteTokenRoute
  Oid4vpIdRoute: typeof Oid4vpIdRoute
  PresentRefRoute: typeof PresentRefRoute
  ReportRefRoute: typeof ReportRefRoute
  SchemasUniversityDegreeRoute: typeof SchemasUniversityDegreeRoute
  SchemasUniversityDegreeCredentialDotjsonRoute: typeof SchemasUniversityDegreeCredentialDotjsonRoute
  StatusIdRoute: typeof StatusIdRoute
  VerifyRefRoute: typeof VerifyRefRoute
  Oid4vciIndexRoute: typeof Oid4vciIndexRoute
  Oid4vpIndexRoute: typeof Oid4vpIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1VerifyRoute: typeof ApiV1VerifyRoute
  CredentialsStatusIdRoute: typeof CredentialsStatusIdRoute
  ApiV1DidWebSlugRoute: typeof ApiV1DidWebSlugRoute
  ApiV1EvidenceRefRoute: typeof ApiV1EvidenceRefRoute
  ApiV1LedgerChainRoute: typeof ApiV1LedgerChainRoute
  ApiV1LedgerProofRoute: typeof ApiV1LedgerProofRouteWithChildren
  ApiV1LedgerVerifyRoute: typeof ApiV1LedgerVerifyRoute
  ApiV1Oid4vciCredentialRoute: typeof ApiV1Oid4vciCredentialRoute
  ApiV1Oid4vciMetadataRoute: typeof ApiV1Oid4vciMetadataRoute
  ApiV1Oid4vciPreviewWalletRoute: typeof ApiV1Oid4vciPreviewWalletRoute
  ApiV1Oid4vciTokenRoute: typeof ApiV1Oid4vciTokenRoute
  ApiV1Oid4vpRequestsRoute: typeof ApiV1Oid4vpRequestsRoute
  ApiV1ReportsRefRoute: typeof ApiV1ReportsRefRoute
  ApiV1Oid4vciOfferTokenRoute: typeof ApiV1Oid4vciOfferTokenRoute
  ApiV1Oid4vpDirectPostIdRoute: typeof ApiV1Oid4vpDirectPostIdRoute
  ApiV1Oid4vpPreviewWalletIdRoute: typeof ApiV1Oid4vpPreviewWalletIdRoute
  ApiV1Oid4vpRequestIdRoute: typeof ApiV1Oid4vpRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sd-jwt': {
      id: '/sd-jwt'
      path: '/sd-jwt'
      fullPath: '/sd-jwt'
      preLoaderRoute: typeof SdJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc2': {
      id: '/soc2'
      path: '/soc2'
      fullPath: '/soc2'
      preLoaderRoute: typeof Soc2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-credential-issuer': {
      id: '/.well-known/openid-credential-issuer'
      path: '/.well-known/openid-credential-issuer'
      fullPath: '/.well-known/openid-credential-issuer'
      preLoaderRoute: typeof DotwellKnownOpenidCredentialIssuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/credentials': {
      id: '/app/credentials'
      path: '/credentials'
      fullPath: '/app/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/issue': {
      id: '/app/issue'
      path: '/issue'
      fullPath: '/app/issue'
      preLoaderRoute: typeof AppIssueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/status': {
      id: '/app/status'
      path: '/status'
      fullPath: '/app/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/did-web/$slug': {
      id: '/did-web/$slug'
      path: '/did-web/$slug'
      fullPath: '/did-web/$slug'
      preLoaderRoute: typeof DidWebSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/did/$multibase': {
      id: '/did/$multibase'
      path: '/did/$multibase'
      fullPath: '/did/$multibase'
      preLoaderRoute: typeof DidMultibaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$ref': {
      id: '/evidence/$ref'
      path: '/evidence/$ref'
      fullPath: '/evidence/$ref'
      preLoaderRoute: typeof EvidenceRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oid4vci/': {
      id: '/oid4vci/'
      path: '/oid4vci'
      fullPath: '/oid4vci/'
      preLoaderRoute: typeof Oid4vciIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oid4vp/': {
      id: '/oid4vp/'
      path: '/oid4vp'
      fullPath: '/oid4vp/'
      preLoaderRoute: typeof Oid4vpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oid4vp/$id': {
      id: '/oid4vp/$id'
      path: '/oid4vp/$id'
      fullPath: '/oid4vp/$id'
      preLoaderRoute: typeof Oid4vpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$ref': {
      id: '/present/$ref'
      path: '/present/$ref'
      fullPath: '/present/$ref'
      preLoaderRoute: typeof PresentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ref': {
      id: '/report/$ref'
      path: '/report/$ref'
      fullPath: '/report/$ref'
      preLoaderRoute: typeof ReportRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/university-degree': {
      id: '/schemas/university-degree'
      path: '/schemas/university-degree'
      fullPath: '/schemas/university-degree'
      preLoaderRoute: typeof SchemasUniversityDegreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/university-degree-credential.json': {
      id: '/schemas/university-degree-credential.json'
      path: '/schemas/university-degree-credential.json'
      fullPath: '/schemas/university-degree-credential.json'
      preLoaderRoute: typeof SchemasUniversityDegreeCredentialDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$id': {
      id: '/status/$id'
      path: '/status/$id'
      fullPath: '/status/$id'
      preLoaderRoute: typeof StatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ref': {
      id: '/verify/$ref'
      path: '/verify/$ref'
      fullPath: '/verify/$ref'
      preLoaderRoute: typeof VerifyRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/verify': {
      id: '/api/v1/verify'
      path: '/api/v1/verify'
      fullPath: '/api/v1/verify'
      preLoaderRoute: typeof ApiV1VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials/status/$id': {
      id: '/credentials/status/$id'
      path: '/credentials/status/$id'
      fullPath: '/credentials/status/$id'
      preLoaderRoute: typeof CredentialsStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/claim/$token': {
      id: '/wallet/claim/$token'
      path: '/claim/$token'
      fullPath: '/wallet/claim/$token'
      preLoaderRoute: typeof WalletClaimTokenRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/api/v1/did-web/$slug': {
      id: '/api/v1/did-web/$slug'
      path: '/api/v1/did-web/$slug'
      fullPath: '/api/v1/did-web/$slug'
      preLoaderRoute: typeof ApiV1DidWebSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence/$ref': {
      id: '/api/v1/evidence/$ref'
      path: '/api/v1/evidence/$ref'
      fullPath: '/api/v1/evidence/$ref'
      preLoaderRoute: typeof ApiV1EvidenceRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ledger/chain': {
      id: '/api/v1/ledger/chain'
      path: '/api/v1/ledger/chain'
      fullPath: '/api/v1/ledger/chain'
      preLoaderRoute: typeof ApiV1LedgerChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ledger/proof': {
      id: '/api/v1/ledger/proof'
      path: '/api/v1/ledger/proof'
      fullPath: '/api/v1/ledger/proof'
      preLoaderRoute: typeof ApiV1LedgerProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ledger/verify': {
      id: '/api/v1/ledger/verify'
      path: '/api/v1/ledger/verify'
      fullPath: '/api/v1/ledger/verify'
      preLoaderRoute: typeof ApiV1LedgerVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vci/credential': {
      id: '/api/v1/oid4vci/credential'
      path: '/api/v1/oid4vci/credential'
      fullPath: '/api/v1/oid4vci/credential'
      preLoaderRoute: typeof ApiV1Oid4vciCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vci/metadata': {
      id: '/api/v1/oid4vci/metadata'
      path: '/api/v1/oid4vci/metadata'
      fullPath: '/api/v1/oid4vci/metadata'
      preLoaderRoute: typeof ApiV1Oid4vciMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vci/preview-wallet': {
      id: '/api/v1/oid4vci/preview-wallet'
      path: '/api/v1/oid4vci/preview-wallet'
      fullPath: '/api/v1/oid4vci/preview-wallet'
      preLoaderRoute: typeof ApiV1Oid4vciPreviewWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vci/token': {
      id: '/api/v1/oid4vci/token'
      path: '/api/v1/oid4vci/token'
      fullPath: '/api/v1/oid4vci/token'
      preLoaderRoute: typeof ApiV1Oid4vciTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vp/requests': {
      id: '/api/v1/oid4vp/requests'
      path: '/api/v1/oid4vp/requests'
      fullPath: '/api/v1/oid4vp/requests'
      preLoaderRoute: typeof ApiV1Oid4vpRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/$ref': {
      id: '/api/v1/reports/$ref'
      path: '/api/v1/reports/$ref'
      fullPath: '/api/v1/reports/$ref'
      preLoaderRoute: typeof ApiV1ReportsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ledger/proof/verify': {
      id: '/api/v1/ledger/proof/verify'
      path: '/verify'
      fullPath: '/api/v1/ledger/proof/verify'
      preLoaderRoute: typeof ApiV1LedgerProofVerifyRouteImport
      parentRoute: typeof ApiV1LedgerProofRoute
    }
    '/api/v1/oid4vci/offer/$token': {
      id: '/api/v1/oid4vci/offer/$token'
      path: '/api/v1/oid4vci/offer/$token'
      fullPath: '/api/v1/oid4vci/offer/$token'
      preLoaderRoute: typeof ApiV1Oid4vciOfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vp/direct-post/$id': {
      id: '/api/v1/oid4vp/direct-post/$id'
      path: '/api/v1/oid4vp/direct-post/$id'
      fullPath: '/api/v1/oid4vp/direct-post/$id'
      preLoaderRoute: typeof ApiV1Oid4vpDirectPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vp/preview-wallet/$id': {
      id: '/api/v1/oid4vp/preview-wallet/$id'
      path: '/api/v1/oid4vp/preview-wallet/$id'
      fullPath: '/api/v1/oid4vp/preview-wallet/$id'
      preLoaderRoute: typeof ApiV1Oid4vpPreviewWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/oid4vp/request/$id': {
      id: '/api/v1/oid4vp/request/$id'
      path: '/api/v1/oid4vp/request/$id'
      fullPath: '/api/v1/oid4vp/request/$id'
      preLoaderRoute: typeof ApiV1Oid4vpRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppIssueRoute: typeof AppIssueRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppStatusRoute: typeof AppStatusRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditRoute: AppAuditRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppIssueRoute: AppIssueRoute,
  AppKeysRoute: AppKeysRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppStatusRoute: AppStatusRoute,
  AppTeamRoute: AppTeamRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WalletRouteRouteChildren {
  WalletIndexRoute: typeof WalletIndexRoute
  WalletClaimTokenRoute: typeof WalletClaimTokenRoute
}

const WalletRouteRouteChildren: WalletRouteRouteChildren = {
  WalletIndexRoute: WalletIndexRoute,
  WalletClaimTokenRoute: WalletClaimTokenRoute,
}

const WalletRouteRouteWithChildren = WalletRouteRoute._addFileChildren(
  WalletRouteRouteChildren,
)

interface ApiV1LedgerProofRouteChildren {
  ApiV1LedgerProofVerifyRoute: typeof ApiV1LedgerProofVerifyRoute
}

const ApiV1LedgerProofRouteChildren: ApiV1LedgerProofRouteChildren = {
  ApiV1LedgerProofVerifyRoute: ApiV1LedgerProofVerifyRoute,
}

const ApiV1LedgerProofRouteWithChildren =
  ApiV1LedgerProofRoute._addFileChildren(ApiV1LedgerProofRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  WalletRouteRoute: WalletRouteRouteWithChildren,
  ChainRoute: ChainRoute,
  ComplianceRoute: ComplianceRoute,
  DevelopersRoute: DevelopersRoute,
  HealthzRoute: HealthzRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  ReadyzRoute: ReadyzRoute,
  SdJwtRoute: SdJwtRoute,
  Soc2Route: Soc2Route,
  TrustRoute: TrustRoute,
  DotwellKnownOpenidCredentialIssuerRoute:
    DotwellKnownOpenidCredentialIssuerRoute,
  DidWebSlugRoute: DidWebSlugRoute,
  DidMultibaseRoute: DidMultibaseRoute,
  EvidenceRefRoute: EvidenceRefRoute,
  InviteTokenRoute: InviteTokenRoute,
  Oid4vpIdRoute: Oid4vpIdRoute,
  PresentRefRoute: PresentRefRoute,
  ReportRefRoute: ReportRefRoute,
  SchemasUniversityDegreeRoute: SchemasUniversityDegreeRoute,
  SchemasUniversityDegreeCredentialDotjsonRoute:
    SchemasUniversityDegreeCredentialDotjsonRoute,
  StatusIdRoute: StatusIdRoute,
  VerifyRefRoute: VerifyRefRoute,
  Oid4vciIndexRoute: Oid4vciIndexRoute,
  Oid4vpIndexRoute: Oid4vpIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1VerifyRoute: ApiV1VerifyRoute,
  CredentialsStatusIdRoute: CredentialsStatusIdRoute,
  ApiV1DidWebSlugRoute: ApiV1DidWebSlugRoute,
  ApiV1EvidenceRefRoute: ApiV1EvidenceRefRoute,
  ApiV1LedgerChainRoute: ApiV1LedgerChainRoute,
  ApiV1LedgerProofRoute: ApiV1LedgerProofRouteWithChildren,
  ApiV1LedgerVerifyRoute: ApiV1LedgerVerifyRoute,
  ApiV1Oid4vciCredentialRoute: ApiV1Oid4vciCredentialRoute,
  ApiV1Oid4vciMetadataRoute: ApiV1Oid4vciMetadataRoute,
  ApiV1Oid4vciPreviewWalletRoute: ApiV1Oid4vciPreviewWalletRoute,
  ApiV1Oid4vciTokenRoute: ApiV1Oid4vciTokenRoute,
  ApiV1Oid4vpRequestsRoute: ApiV1Oid4vpRequestsRoute,
  ApiV1ReportsRefRoute: ApiV1ReportsRefRoute,
  ApiV1Oid4vciOfferTokenRoute: ApiV1Oid4vciOfferTokenRoute,
  ApiV1Oid4vpDirectPostIdRoute: ApiV1Oid4vpDirectPostIdRoute,
  ApiV1Oid4vpPreviewWalletIdRoute: ApiV1Oid4vpPreviewWalletIdRoute,
  ApiV1Oid4vpRequestIdRoute: ApiV1Oid4vpRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
