/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalletRouteRouteImport } from './routes/wallet/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCredentialsRouteImport } from './routes/app/credentials'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppIssueRouteImport } from './routes/app/issue'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as AppLedgerRouteImport } from './routes/app/ledger'
import { Route as DidMultibaseRouteImport } from './routes/did.$multibase'
import { Route as PresentRefRouteImport } from './routes/present.$ref'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyRefRouteImport } from './routes/verify/$ref'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WalletClaimTokenRouteImport } from './routes/wallet/claim.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRouteRoute = WalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssueRoute = AppIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const DidMultibaseRoute = DidMultibaseRouteImport.update({
  id: '/did/$multibase',
  path: '/did/$multibase',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRefRoute = PresentRefRouteImport.update({
  id: '/present/$ref',
  path: '/present/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRefRoute = VerifyRefRouteImport.update({
  id: '/verify/$ref',
  path: '/verify/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletClaimTokenRoute = WalletClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => WalletRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/present/$ref': typeof PresentRefRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/present/$ref': typeof PresentRefRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app': typeof AppIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/trust': typeof TrustRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/issue': typeof AppIssueRoute
  '/app/keys': typeof AppKeysRoute
  '/app/ledger': typeof AppLedgerRoute
  '/did/$multibase': typeof DidMultibaseRoute
  '/present/$ref': typeof PresentRefRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/app/': typeof AppIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/wallet/claim/$token': typeof WalletClaimTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/wallet'
    | '/login'
    | '/trust'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/did/$multibase'
    | '/present/$ref'
    | '/verify/$ref'
    | '/app/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/wallet/claim/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/trust'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/did/$multibase'
    | '/present/$ref'
    | '/verify/$ref'
    | '/app'
    | '/verify'
    | '/wallet'
    | '/api/auth/$'
    | '/wallet/claim/$token'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/wallet'
    | '/login'
    | '/trust'
    | '/app/audit'
    | '/app/credentials'
    | '/app/documents'
    | '/app/issue'
    | '/app/keys'
    | '/app/ledger'
    | '/did/$multibase'
    | '/present/$ref'
    | '/verify/$ref'
    | '/app/'
    | '/verify/'
    | '/wallet/'
    | '/api/auth/$'
    | '/wallet/claim/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WalletRouteRoute: typeof WalletRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrustRoute: typeof TrustRoute
  DidMultibaseRoute: typeof DidMultibaseRoute
  PresentRefRoute: typeof PresentRefRoute
  VerifyRefRoute: typeof VerifyRefRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/credentials': {
      id: '/app/credentials'
      path: '/credentials'
      fullPath: '/app/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/issue': {
      id: '/app/issue'
      path: '/issue'
      fullPath: '/app/issue'
      preLoaderRoute: typeof AppIssueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/did/$multibase': {
      id: '/did/$multibase'
      path: '/did/$multibase'
      fullPath: '/did/$multibase'
      preLoaderRoute: typeof DidMultibaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$ref': {
      id: '/present/$ref'
      path: '/present/$ref'
      fullPath: '/present/$ref'
      preLoaderRoute: typeof PresentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ref': {
      id: '/verify/$ref'
      path: '/verify/$ref'
      fullPath: '/verify/$ref'
      preLoaderRoute: typeof VerifyRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/claim/$token': {
      id: '/wallet/claim/$token'
      path: '/claim/$token'
      fullPath: '/wallet/claim/$token'
      preLoaderRoute: typeof WalletClaimTokenRouteImport
      parentRoute: typeof WalletRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppIssueRoute: typeof AppIssueRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppIssueRoute: AppIssueRoute,
  AppKeysRoute: AppKeysRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WalletRouteRouteChildren {
  WalletIndexRoute: typeof WalletIndexRoute
  WalletClaimTokenRoute: typeof WalletClaimTokenRoute
}

const WalletRouteRouteChildren: WalletRouteRouteChildren = {
  WalletIndexRoute: WalletIndexRoute,
  WalletClaimTokenRoute: WalletClaimTokenRoute,
}

const WalletRouteRouteWithChildren = WalletRouteRoute._addFileChildren(
  WalletRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  WalletRouteRoute: WalletRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TrustRoute: TrustRoute,
  DidMultibaseRoute: DidMultibaseRoute,
  PresentRefRoute: PresentRefRoute,
  VerifyRefRoute: VerifyRefRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
